### ISSUE TITLE
Game doesn't allow to play with 1 hand only

### ISSUE THREAD

**Issue by Hozhyi** [telador/Word_game#2]
![image](https://user-images.githubusercontent.com/7387800/102865949-2e93d200-443f-11eb-9092-275451d9673b.png)

**Comment by Hozhyi** [comment]
![image](https://user-images.githubusercontent.com/7387800/102866099-69960580-443f-11eb-846b-fae2a9846a7e.png)

**Comment by telador** [comment]
Fixed in " Changed input of "num_of_hands". "
